services:
    _defaults:
        public: true

    Oro\Bundle\ContactUsBundle\Controller\ContactRequestController:
        tags: ['controller.service_arguments']

    Oro\Bundle\ContactUsBundle\Controller\ContactReasonController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: doctrine.orm.entity_manager }
