features:
    sales_lead:
        label: oro.sales.lead.feature.label
        description: oro.sales.lead.feature.description
        toggle: oro_sales.lead_feature_enabled
        routes:
            - oro_sales_lead_view
            - oro_sales_lead_info
            - oro_sales_lead_create
            - oro_sales_lead_update
            - oro_sales_lead_index
            - oro_sales_widget_account_leads
            - oro_sales_lead_data_channel_aware_create
            - oro_sales_lead_disqualify
            - oro_sales_lead_convert_to_opportunity
        workflows:
            - b2b_flow_lead
        processes:
            - convert_mailbox_email_to_lead
        api_resources:
            - Oro\Bundle\SalesBundle\Entity\Lead
            - Oro\Bundle\SalesBundle\Entity\LeadAddress
            - Oro\Bundle\SalesBundle\Entity\LeadEmail
            - Oro\Bundle\SalesBundle\Entity\LeadPhone
            - Extend\Entity\EV_Lead_Status
            - Extend\Entity\EV_Lead_Source
        entities:
            - Oro\Bundle\SalesBundle\Entity\Lead
            - Oro\Bundle\SalesBundle\Entity\LeadAddress
            - Oro\Bundle\SalesBundle\Entity\LeadEmail
            - Oro\Bundle\SalesBundle\Entity\LeadPhone
        placeholder_items:
            - leads_launchpad
        dashboard_widgets:
            - leads_list
            - campaigns_leads
            - campaigns_by_close_revenue
            - quick_launchpad.leads
            - lead_statistics
        navigation_items:
            - application_menu.reports_tab.static_reports_tab.leads_report_tab.leads_by_date

    sales_opportunity:
        label: oro.sales.opportunity.feature.label
        description: oro.sales.opportunity.feature.description
        toggle: oro_sales.opportunity_feature_enabled
        routes:
            - oro_sales_opportunity_view
            - oro_sales_opportunity_info
            - oro_sales_opportunity_create
            - oro_sales_opportunity_update
            - oro_sales_opportunity_index
            - oro_sales_opportunity_data_channel_aware_create
            - oro_sales_opportunity_customer_aware_create
        workflows:
            - opportunity_flow
        api_resources:
            - Oro\Bundle\SalesBundle\Entity\Opportunity
            - Oro\Bundle\SalesBundle\Entity\OpportunityCloseReason
            - Extend\Entity\EV_Opportunity_Status
        entities:
            - Oro\Bundle\SalesBundle\Entity\Opportunity
            - Oro\Bundle\SalesBundle\Entity\OpportunityCloseReason
        configuration:
            - opportunity_status_probabilities
            - display_settings
        placeholder_items:
            - opportunities_launchpad
            - oro_sales_create_opportunity_link
            - oro_sales_create_opportunity_button
        dashboard_widgets:
            - quick_launchpad.opportunities
            - opportunities_by_lead_source_chart
            - opportunities_by_state
            - campaigns_opportunity
            - forecast_of_opportunities
            - average_lifetime_sales_chart
            - campaigns_by_close_revenue
            - opportunities_list
            - opportunity_statistics
        navigation_items:
            - application_menu.reports_tab.static_reports_tab.opportunities_report_tab.opportunities_by_status
            - application_menu.reports_tab.static_reports_tab.accounts_report_tab.accounts_by_opportunities
            - application_menu.reports_tab.static_reports_tab.opportunities_report_tab.won_by_period
            - application_menu.reports_tab.static_reports_tab.opportunities_report_tab.total_forecast
            - application_menu.reports_tab.static_reports_tab.accounts_report_tab.accounts_life_time_value
        commands:
            - oro:b2b:lifetime:recalculate
